en:
  errors:
    messages:
      record_invalid: "%{model} invalid"
      unique_for_organization: "already exists for this organization"
